/**
 * Firebase 샘플 데이터 시딩 스크립트
 * 사용법: node firestore.seed.js (firebase-admin 설치 후)
 * 또는 Firebase Console > Firestore > 데이터 탭에서 직접 추가
 */

const SAMPLE_VENUES = [
  {
    name: '클럽 옥타곤',
    name_en: 'Club Octagon',
    slug: 'octagon',
    region: 'gangnam',
    categories: ['edm'],
    address: '서울 강남구 논현로 645',
    entrance_fee_weekday: 20000,
    entrance_fee_weekend: 30000,
    music_genres: ['EDM', 'House', 'Tech House'],
    open_days: ['목', '금', '토', '일'],
    open_time: '22:00',
    close_time: '다음날 07:00',
    instagram_handle: 'octagonseoul',
    description: '아시아 최고 수준의 EDM 클럽. DJ Mag 세계 Top 10 선정.',
    description_en: "Asia's top-rated EDM club. Ranked in DJ Mag World Top 10.",
    is_active: true,
    is_verified: true,
    age_restriction: 19,
    images: [],
    instagram_connected: false,
    owner_id: null,
  },
  {
    name: '케이크샵',
    name_en: 'Cakeshop',
    slug: 'cakeshop',
    region: 'itaewon',
    categories: ['hiphop'],
    address: '서울 용산구 이태원로 134 지하 1층',
    entrance_fee_weekday: 15000,
    entrance_fee_weekend: 20000,
    music_genres: ['Hip-Hop', 'House', 'Trap', 'Bass Music'],
    open_days: ['금', '토'],
    open_time: '23:00',
    close_time: '다음날 06:00',
    instagram_handle: 'cakeshopseoul',
    description: '2018 Best Club Seoul 수상. 힙합·하우스·트랩·베이스뮤직 특화.',
    description_en: "Winner of Best Club Seoul 2018. Specializes in hip-hop, house, trap and bass music.",
    is_active: true,
    is_verified: true,
    age_restriction: 19,
    images: [],
    instagram_connected: false,
    owner_id: null,
  },
  {
    name: '헨즈 클럽',
    name_en: 'The Henz Club',
    slug: 'henz-club',
    region: 'hongdae',
    categories: ['hiphop'],
    address: '서울 마포구 와우산로 64 지하 1층',
    entrance_fee_weekday: 10000,
    entrance_fee_weekend: 15000,
    music_genres: ['Hip-Hop', 'R&B', 'Bass Music'],
    open_days: ['금', '토'],
    open_time: '22:00',
    close_time: '다음날 05:00',
    instagram_handle: 'thehenzclub',
    description: '언더그라운드 힙합 씬의 중심. Henz Clothing 운영. 금연 클럽.',
    description_en: "The heart of Seoul's underground hip-hop scene. Smoke-free club.",
    is_active: true,
    is_verified: true,
    age_restriction: 19,
    images: [],
    instagram_connected: false,
    owner_id: null,
  },
  {
    name: '소프 서울',
    name_en: 'Soap Seoul',
    slug: 'soap-seoul',
    region: 'itaewon',
    categories: ['techno'],
    address: '서울 용산구 이태원로 217 지하 2층',
    entrance_fee_weekday: 15000,
    entrance_fee_weekend: 20000,
    music_genres: ['House', 'Techno', 'Deep House'],
    open_days: ['금', '토'],
    open_time: '23:00',
    close_time: '다음날 06:00',
    instagram_handle: 'soapseoul',
    description: '이태원 언더그라운드 하우스·테크노 클럽. Soap Records 레이블 보유.',
    description_en: "Underground house & techno club in Itaewon. Home of Soap Records label.",
    is_active: true,
    is_verified: true,
    age_restriction: 19,
    images: [],
    instagram_connected: false,
    owner_id: null,
  },
  {
    name: 'NB2',
    name_en: 'Noise Basement 2',
    slug: 'nb2',
    region: 'hongdae',
    categories: ['hiphop', 'edm', 'kpop'],
    address: '서울 마포구 와우산로 72',
    entrance_fee_weekday: 15000,
    entrance_fee_weekend: 20000,
    music_genres: ['Hip-Hop', 'R&B', 'EDM', 'K-POP'],
    open_days: ['월', '화', '수', '목', '금', '토', '일'],
    open_time: '22:00',
    close_time: '다음날 06:00',
    instagram_handle: 'clubnb_official',
    description: '1999년부터 운영된 홍대의 상징적 클럽. 힙합·R&B·EDM·K-POP. YG 운영.',
    description_en: "Iconic Hongdae club since 1999. Hip-hop, R&B, EDM and K-POP. Operated by YG.",
    is_active: true,
    is_verified: true,
    age_restriction: 19,
    images: [],
    instagram_connected: false,
    owner_id: null,
  },
  {
    name: '파우스트',
    name_en: 'Faust',
    slug: 'faust',
    region: 'itaewon',
    categories: ['techno'],
    address: '서울 용산구 보광로60길 7, 3층',
    entrance_fee_weekday: 15000,
    entrance_fee_weekend: 20000,
    music_genres: ['Techno', 'Industrial', 'Dark Techno'],
    open_days: ['금', '토'],
    open_time: '23:00',
    close_time: null,
    instagram_handle: 'faustseoul',
    description: '이태원 언더그라운드 테크노 클럽. 어둡고 강렬한 사운드.',
    description_en: "Underground techno club in Itaewon. Dark and intense sound.",
    is_active: true,
    is_verified: true,
    age_restriction: 19,
    images: [],
    instagram_connected: false,
    owner_id: null,
  },
  {
    name: '클럽 아르떼',
    name_en: 'Club Arte',
    slug: 'arte',
    region: 'gangnam',
    categories: ['edm', 'hiphop'],
    address: '서울 서초구 강남대로 415 지하 1층',
    entrance_fee_weekday: 15000,
    entrance_fee_weekend: 20000,
    music_genres: ['EDM', 'Hip-Hop', 'House'],
    open_days: ['수', '목', '금', '토'],
    open_time: '22:00',
    close_time: '다음날 05:00',
    instagram_handle: 'arte_seoul_official',
    description: '강남역 인근 클럽. 2층 룸 구비. 접근성 최고.',
    description_en: "Club near Gangnam Station. Private rooms available. Best accessibility.",
    is_active: true,
    is_verified: true,
    age_restriction: 19,
    images: [],
    instagram_connected: false,
    owner_id: null,
  },
  {
    name: '루프탑 클라우드',
    name_en: 'Rooftop Cloud',
    slug: 'rooftop-cloud',
    region: 'gangnam',
    categories: ['rooftop'],
    address: '서울 강남구 테헤란로25길 10, 21층',
    entrance_fee_weekday: null,
    entrance_fee_weekend: null,
    music_genres: ['Chill', 'Lounge', 'House'],
    open_days: ['화', '수', '목', '금', '토', '일'],
    open_time: '18:00',
    close_time: '01:00',
    instagram_handle: null,
    description: '국내 최초 루프탑바. 강남 야경과 함께하는 칵테일.',
    description_en: "Korea's first rooftop bar. Cocktails with Gangnam night view.",
    is_active: true,
    is_verified: true,
    age_restriction: 19,
    images: [],
    instagram_connected: false,
    owner_id: null,
  },
  {
    name: 'BOO',
    name_en: 'BOO Seoul',
    slug: 'boo-seoul',
    region: 'euljiro',
    categories: ['hiphop', 'kpop'],
    address: '서울 중구 을지로3가 95-4 B1',
    entrance_fee_weekday: 15000,
    entrance_fee_weekend: 15000,
    music_genres: ['Hip-Hop', 'K-POP', 'R&B'],
    open_days: ['금', '토'],
    open_time: '22:00',
    close_time: '다음날 05:00',
    instagram_handle: null,
    description: '을지로 힙합·K-POP 클럽. 을지로 나이트라이프의 핵심.',
    description_en: "Hip-hop & K-POP club in Euljiro. Core of Euljiro nightlife.",
    is_active: true,
    is_verified: false,
    age_restriction: 19,
    images: [],
    instagram_connected: false,
    owner_id: null,
  },
  {
    name: '브라운',
    name_en: 'Brown',
    slug: 'brown-hongdae',
    region: 'hongdae',
    categories: ['hiphop'],
    address: '서울 마포구 상수동 86-22, 5층',
    entrance_fee_weekday: 10000,
    entrance_fee_weekend: 15000,
    music_genres: ['Hip-Hop', 'R&B', 'Old School'],
    open_days: ['목', '금', '토'],
    open_time: '22:00',
    close_time: '다음날 05:00',
    instagram_handle: null,
    description: '올드스쿨 힙합·R&B 전문. 유명 래퍼들이 자주 찾는 홍대 힙합 성지.',
    description_en: "Old school hip-hop & R&B specialist. A Hongdae hip-hop mecca.",
    is_active: true,
    is_verified: false,
    age_restriction: 19,
    images: [],
    instagram_connected: false,
    owner_id: null,
  },
];

// Firebase Admin SDK로 시딩:
// const admin = require('firebase-admin');
// const serviceAccount = require('./serviceAccountKey.json');
// admin.initializeApp({ credential: admin.credential.cert(serviceAccount) });
// const db = admin.firestore();
// SAMPLE_VENUES.forEach(async v => {
//   await db.collection('venues').add({ ...v, created_at: admin.firestore.FieldValue.serverTimestamp(), updated_at: admin.firestore.FieldValue.serverTimestamp() });
// });

// 또는 Firebase Console에서 직접 입력
module.exports = SAMPLE_VENUES;
