/**
 * Firestore 샘플 데이터 시딩 스크립트
 * 사용법: node seed.js
 */

const { initializeApp } = require('firebase/app');
const {
  getFirestore,
  collection,
  addDoc,
  getDocs,
  query,
  where,
  serverTimestamp,
} = require('firebase/firestore');

// Firebase 설정 (lounge-35d0a 프로젝트)
const firebaseConfig = {
  apiKey: 'AIzaSyDVEgs7lrzGLJBCUODOuX0JmxIa4TCYpEg',
  authDomain: 'lounge-35d0a.firebaseapp.com',
  projectId: 'lounge-35d0a',
  storageBucket: 'lounge-35d0a.firebasestorage.app',
  messagingSenderId: '885778472477',
  appId: '1:885778472477:web:cb49b28058adb8d141b0f4',
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const SAMPLE_VENUES = [
  {
    name: '클럽 옥타곤',
    name_en: 'Club Octagon',
    slug: 'octagon',
    region: 'gangnam',
    categories: ['edm'],
    address: '서울 강남구 논현로 645',
    lat: 37.5105,
    lng: 127.0285,
    entrance_fee_weekday: 20000,
    entrance_fee_weekend: 30000,
    music_genres: ['EDM', 'House', 'Tech House'],
    dress_code: '단정한 복장',
    age_restriction: 19,
    open_days: ['목', '금', '토', '일'],
    open_time: '22:00',
    close_time: '다음날 07:00',
    instagram_handle: 'octagonseoul',
    instagram_connected: false,
    website_url: 'https://www.octagonseoul.com',
    phone: null,
    capacity: 2500,
    description: '아시아 최고 수준의 EDM 클럽. DJ Mag 세계 Top 10 선정.',
    description_en: "Asia's top-rated EDM club. Ranked in DJ Mag World Top 10.",
    cover_image_url: null,
    images: [],
    is_active: true,
    is_verified: true,
    owner_id: null,
  },
  {
    name: '케이크샵',
    name_en: 'Cakeshop',
    slug: 'cakeshop',
    region: 'itaewon',
    categories: ['hiphop'],
    address: '서울 용산구 이태원로 134 지하 1층',
    lat: 37.5347,
    lng: 126.9945,
    entrance_fee_weekday: 15000,
    entrance_fee_weekend: 20000,
    music_genres: ['Hip-Hop', 'House', 'Trap', 'Bass Music'],
    dress_code: null,
    age_restriction: 19,
    open_days: ['금', '토'],
    open_time: '23:00',
    close_time: '다음날 06:00',
    instagram_handle: 'cakeshopseoul',
    instagram_connected: false,
    website_url: null,
    phone: null,
    capacity: 300,
    description: '2018 Best Club Seoul 수상. 힙합·하우스·트랩·베이스뮤직 특화.',
    description_en: "Winner of Best Club Seoul 2018. Specializes in hip-hop, house, trap and bass music.",
    cover_image_url: null,
    images: [],
    is_active: true,
    is_verified: true,
    owner_id: null,
  },
  {
    name: '헨즈 클럽',
    name_en: 'The Henz Club',
    slug: 'henz-club',
    region: 'hongdae',
    categories: ['hiphop'],
    address: '서울 마포구 와우산로 64 지하 1층',
    lat: 37.5494,
    lng: 126.9230,
    entrance_fee_weekday: 10000,
    entrance_fee_weekend: 15000,
    music_genres: ['Hip-Hop', 'R&B', 'Bass Music'],
    dress_code: null,
    age_restriction: 19,
    open_days: ['금', '토'],
    open_time: '22:00',
    close_time: '다음날 05:00',
    instagram_handle: 'thehenzclub',
    instagram_connected: false,
    website_url: null,
    phone: null,
    capacity: 200,
    description: '언더그라운드 힙합 씬의 중심. Henz Clothing 운영. 금연 클럽.',
    description_en: "The heart of Seoul's underground hip-hop scene. Smoke-free club.",
    cover_image_url: null,
    images: [],
    is_active: true,
    is_verified: true,
    owner_id: null,
  },
  {
    name: '소프 서울',
    name_en: 'Soap Seoul',
    slug: 'soap-seoul',
    region: 'itaewon',
    categories: ['techno'],
    address: '서울 용산구 이태원로 217 지하 2층',
    lat: 37.5347,
    lng: 126.9945,
    entrance_fee_weekday: 15000,
    entrance_fee_weekend: 20000,
    music_genres: ['House', 'Techno', 'Deep House'],
    dress_code: null,
    age_restriction: 19,
    open_days: ['금', '토'],
    open_time: '23:00',
    close_time: '다음날 06:00',
    instagram_handle: 'soapseoul',
    instagram_connected: false,
    website_url: null,
    phone: null,
    capacity: 150,
    description: '이태원 언더그라운드 하우스·테크노 클럽. Soap Records 레이블 보유.',
    description_en: "Underground house & techno club in Itaewon. Home of Soap Records label.",
    cover_image_url: null,
    images: [],
    is_active: true,
    is_verified: true,
    owner_id: null,
  },
  {
    name: 'NB2',
    name_en: 'Noise Basement 2',
    slug: 'nb2',
    region: 'hongdae',
    categories: ['hiphop', 'edm', 'kpop'],
    address: '서울 마포구 와우산로 72',
    lat: 37.5499,
    lng: 126.9235,
    entrance_fee_weekday: 15000,
    entrance_fee_weekend: 20000,
    music_genres: ['Hip-Hop', 'R&B', 'EDM', 'K-POP'],
    dress_code: null,
    age_restriction: 19,
    open_days: ['월', '화', '수', '목', '금', '토', '일'],
    open_time: '22:00',
    close_time: '다음날 06:00',
    instagram_handle: 'clubnb_official',
    instagram_connected: false,
    website_url: null,
    phone: null,
    capacity: 500,
    description: '1999년부터 운영된 홍대의 상징적 클럽. 힙합·R&B·EDM·K-POP. YG 운영.',
    description_en: "Iconic Hongdae club since 1999. Hip-hop, R&B, EDM and K-POP. Operated by YG.",
    cover_image_url: null,
    images: [],
    is_active: true,
    is_verified: true,
    owner_id: null,
  },
  {
    name: '파우스트',
    name_en: 'Faust',
    slug: 'faust',
    region: 'itaewon',
    categories: ['techno'],
    address: '서울 용산구 보광로60길 7, 3층',
    lat: 37.5346,
    lng: 126.9949,
    entrance_fee_weekday: 15000,
    entrance_fee_weekend: 20000,
    music_genres: ['Techno', 'Industrial', 'Dark Techno'],
    dress_code: '올블랙 권장',
    age_restriction: 19,
    open_days: ['금', '토'],
    open_time: '23:00',
    close_time: null,
    instagram_handle: 'faustseoul',
    instagram_connected: false,
    website_url: null,
    phone: null,
    capacity: 180,
    description: '이태원 언더그라운드 테크노 클럽. 어둡고 강렬한 사운드.',
    description_en: "Underground techno club in Itaewon. Dark and intense sound.",
    cover_image_url: null,
    images: [],
    is_active: true,
    is_verified: true,
    owner_id: null,
  },
  {
    name: '클럽 아르떼',
    name_en: 'Club Arte',
    slug: 'arte',
    region: 'gangnam',
    categories: ['edm', 'hiphop'],
    address: '서울 서초구 강남대로 415 지하 1층',
    lat: 37.4967,
    lng: 127.0276,
    entrance_fee_weekday: 15000,
    entrance_fee_weekend: 20000,
    music_genres: ['EDM', 'Hip-Hop', 'House'],
    dress_code: null,
    age_restriction: 19,
    open_days: ['수', '목', '금', '토'],
    open_time: '22:00',
    close_time: '다음날 05:00',
    instagram_handle: 'arte_seoul_official',
    instagram_connected: false,
    website_url: null,
    phone: null,
    capacity: 800,
    description: '강남역 인근 클럽. 2층 룸 구비. 접근성 최고.',
    description_en: "Club near Gangnam Station. Private rooms available. Best accessibility.",
    cover_image_url: null,
    images: [],
    is_active: true,
    is_verified: true,
    owner_id: null,
  },
  {
    name: '루프탑 클라우드',
    name_en: 'Rooftop Cloud',
    slug: 'rooftop-cloud',
    region: 'gangnam',
    categories: ['rooftop'],
    address: '서울 강남구 테헤란로25길 10, 21층',
    lat: 37.5043,
    lng: 127.0275,
    entrance_fee_weekday: null,
    entrance_fee_weekend: null,
    music_genres: ['Chill', 'Lounge', 'House'],
    dress_code: '스마트 캐주얼',
    age_restriction: 19,
    open_days: ['화', '수', '목', '금', '토', '일'],
    open_time: '18:00',
    close_time: '01:00',
    instagram_handle: null,
    instagram_connected: false,
    website_url: null,
    phone: null,
    capacity: 120,
    description: '국내 최초 루프탑바. 강남 야경과 함께하는 칵테일.',
    description_en: "Korea's first rooftop bar. Cocktails with Gangnam night view.",
    cover_image_url: null,
    images: [],
    is_active: true,
    is_verified: true,
    owner_id: null,
  },
  {
    name: 'BOO',
    name_en: 'BOO Seoul',
    slug: 'boo-seoul',
    region: 'euljiro',
    categories: ['hiphop', 'kpop'],
    address: '서울 중구 을지로3가 95-4 B1',
    lat: 37.5665,
    lng: 126.9934,
    entrance_fee_weekday: 15000,
    entrance_fee_weekend: 15000,
    music_genres: ['Hip-Hop', 'K-POP', 'R&B'],
    dress_code: null,
    age_restriction: 19,
    open_days: ['금', '토'],
    open_time: '22:00',
    close_time: '다음날 05:00',
    instagram_handle: null,
    instagram_connected: false,
    website_url: null,
    phone: null,
    capacity: 250,
    description: '을지로 힙합·K-POP 클럽. 을지로 나이트라이프의 핵심.',
    description_en: "Hip-hop & K-POP club in Euljiro. Core of Euljiro nightlife.",
    cover_image_url: null,
    images: [],
    is_active: true,
    is_verified: false,
    owner_id: null,
  },
  {
    name: '브라운',
    name_en: 'Brown',
    slug: 'brown-hongdae',
    region: 'hongdae',
    categories: ['hiphop'],
    address: '서울 마포구 상수동 86-22, 5층',
    lat: 37.5479,
    lng: 126.9222,
    entrance_fee_weekday: 10000,
    entrance_fee_weekend: 15000,
    music_genres: ['Hip-Hop', 'R&B', 'Old School'],
    dress_code: null,
    age_restriction: 19,
    open_days: ['목', '금', '토'],
    open_time: '22:00',
    close_time: '다음날 05:00',
    instagram_handle: null,
    instagram_connected: false,
    website_url: null,
    phone: null,
    capacity: 150,
    description: '올드스쿨 힙합·R&B 전문. 유명 래퍼들이 자주 찾는 홍대 힙합 성지.',
    description_en: "Old school hip-hop & R&B specialist. A Hongdae hip-hop mecca.",
    cover_image_url: null,
    images: [],
    is_active: true,
    is_verified: false,
    owner_id: null,
  },
];

async function seed() {
  console.log('🔥 Firestore 시딩 시작...\n');

  // 이미 데이터가 있는 slug 확인 (중복 방지)
  const existingSlugs = new Set();
  const snap = await getDocs(collection(db, 'venues'));
  snap.forEach(d => existingSlugs.add(d.data().slug));

  if (existingSlugs.size > 0) {
    console.log(`⚠️  이미 ${existingSlugs.size}개 업장이 Firestore에 있습니다.`);
    console.log('   slug 중복인 업장은 건너뜁니다.\n');
  }

  let added = 0;
  let skipped = 0;

  for (const venue of SAMPLE_VENUES) {
    if (existingSlugs.has(venue.slug)) {
      console.log(`⏭️  건너뜀: ${venue.name} (이미 존재)`);
      skipped++;
      continue;
    }

    try {
      const docRef = await addDoc(collection(db, 'venues'), {
        ...venue,
        created_at: serverTimestamp(),
        updated_at: serverTimestamp(),
      });
      console.log(`✅ 추가됨: ${venue.name} (${venue.region}) → ID: ${docRef.id}`);
      added++;
    } catch (err) {
      console.error(`❌ 실패: ${venue.name} →`, err.message);
    }
  }

  console.log(`\n🎉 완료! 추가: ${added}개 / 건너뜀: ${skipped}개`);
  process.exit(0);
}

seed().catch(err => {
  console.error('치명적 오류:', err);
  process.exit(1);
});
